"""add api_keys and settings tables

Revision ID: fe318c5adc66
Revises: da0347b742ea
Create Date: 2026-05-05 13:13:05.497445

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe318c5adc66'
down_revision: Union[str, Sequence[str], None] = 'da0347b742ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_keys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('key', sa.Text(), nullable=False),
    sa.Column('stage_a_model', sa.String(length=100), nullable=True),
    sa.Column('stage_b_model', sa.String(length=100), nullable=True),
    sa.Column('last_validated', sa.DateTime(), nullable=True),
    sa.Column('last_validation_status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider')
    )
    op.create_table('settings',
    sa.Column('key', sa.String(length=50), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('settings')
    op.drop_table('api_keys')
    # ### end Alembic commands ###
